Endret ci.yml for trigging av git action test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -35,14 +35,20 @@ jobs:
     - name: Create and activate virtual environment
       run: |
         python -m venv .venv
-        source .venv/bin/activate  # For Linux/Mac
-        .venv\Scripts\activate     # For Windows
+        if [ -f ".venv/bin/activate" ]; then
+          source .venv/bin/activate
+        elif [ -f ".venv/Scripts/activate" ]; then
+          .venv/Scripts/activate
+        else
+          echo "Virtual environment activation script not found."
+          exit 1
+        fi
 
     - name: Install maturin
       run: pip install maturin
 
     - name: Build and install Rust module
-      run: maturin develop
+      run: maturin develop --bindings pyo3
 
     - name: Install Python test dependencies
       run: pip install pytest
